### ISSUE TITLE
[Milestone] v1

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/common-min-api#1]
- [ ] webidl-domexception
- [ ] html-timers
- [ ] html-microtask-queuing
- [ ] html-structured-clonin
- [ ] html-btoa
- [ ] console
- [ ] html-system-state
- [ ] encoding
- [ ] streams
- [ ] fileapi
- [ ] url
- [ ] dom-aborting-ongoing-activities
- [ ] fetch
- [ ] urlpattern
- [ ] webcrypto
- [ ] compression

**Comment by jcbhmr** [comment]
webidl-domexception: https://github.com/jimmywarting/node-domexception
